### ISSUE TITLE
About the generalization of the LAD?

### ISSUE THREAD

**Issue by JCZ404** [cybercore-co-ltd/CoLAD#10]
Hi, Thanks for such great work. I wonder if you test your method proposed in the paper on recently proposed advanced DETR-based object detectors. In DETR-based detectors, the object queries are defined as positive samples or negative samples by Hungarian Matching, which is a prediction-aware label assignment method. Besides, DETR takes the set-prediction formulation, and the object queries of student and teacher models have no certain correspondence. So, I doubt the generalization of your method on DETR-based detectors for the following two reasons: (1) due to the prediction-aware label assignment, the quality of the assignment highly depends on the model's prediction, so, the student with a lower performance model may not be able to distillate effective knowledge to the teacher model with higher performance as claimed in your paper; (2) due the unordered object queries, it cannot directly take the assignment results of teacher model to provide supervision for the student model. Hope to receive your reply.

**Comment by chuong98** [comment]
Hi thanks for your question.
+ We haven't tried LAD with DETR-based methods, mainly because DETRs are kind of slower and consume more memory than CNN-based method, thus not really suitable for industrial applications and edge devices.
+ From academic research aspect, I believe the principle of LAD still works if the teacher is well trained, because the point of LAD is to make the assignment more consistent. 
+ You are right, CoLAD may not work well with Hungarian-assignment, since Hungarian assignment is one-to-one matching and cause very noisy assignment at the beginning, which then destabilize the training for both teacher and student.
Indeed, recent research now try to add back one-to-many assignment to DETR and show that this helps DETR converge faster. So, I personally don't think Hungarian matching is a good approach for training Obj Detection. In short, DETR is good because it adopts the Transformer architecture, not because of the Hungarian-assignment
